var doc = UnityEngine.Object.FindFirstObjectByType<UnityEngine.UIElements.UIDocument>();
var ps = doc.panelSettings;
var rt = ps.targetTexture;
var prev = RenderTexture.active;
RenderTexture.active = rt;
var tex = new Texture2D(rt.width, rt.height, TextureFormat.RGB24, false);
tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
tex.Apply();
RenderTexture.active = prev;
System.IO.File.WriteAllBytes(@"OUTPATH", tex.EncodeToPNG());
ps.targetTexture = null;
Camera.main.targetTexture = null;
UnityEngine.Object.DestroyImmediate(tex);
rt.Release();
return "saved";
